### ISSUE TITLE
Could not connect to + 192.168.4.1

### ISSUE THREAD

**Issue by DemianTinkiel** [Tristan79/iBrew#19]
As soon as I start any of the interfaces or run any command in console I get Could not connect to + 192.168.4.1
full stack-trace:
```  
Starting please wait...

2016-11-13 11:28:13,098 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1250, in connect
    self.__socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2016-11-13 11:28:13,100 - DEBUG - timed out
2016-11-13 11:28:13,101 - ERROR - [192.168.4.1] Could not connect to + 192.168.4.1
Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1250, in connect
    self.__socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

Could not connect to + 192.168.4.1
2016-11-13 11:28:13,103 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 47, in new
    r = fn(*args, **kwargs)
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1258, in connect
    raise SmarterError(0,"Could not connect to + " + self.host)
SmarterError

2016-11-13 11:28:13,105 - DEBUG -
2016-11-13 11:28:13,106 - DEBUG -
2016-11-13 11:28:13,107 - INFO - iBrew: Could not connect to [192.168.4.1]
Traceback (most recent call last):
  File "/home/pi/iBrew/iBrewConsole.py", line 480, in execute
    self.client.connect()
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 52, in new
    raise e
SmarterError

Could not write message not connected
2016-11-13 11:28:13,111 - DEBUG -
2016-11-13 11:28:13,112 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/iBrewConsole.py", line 511, in execute
    self.client.device_all_settings()
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 2359, in device_all_settings
    raise e
SmarterError

iBrew: Could not init values
```

**Comment by Tristan79** [comment]
I still have to clean up the error code, its debug mode ;-) 

The short error story is:
You either did not supply an ip as argument or it is the wrong one (not working, unreachable) and it tries the default ip, which also does not work (at least it tried ;-). 

If you have only one appliance it will auto detect the ip, if you have two or more you have to supply a correct ip of the machine you are going to use (think static ip if you are going to script). 

```
MacBook-Pro:iBrew Tristan$ ./ibrew list
[10.0.0.3:2016-11-13 12:38:24] Found iKettle 2.0 (iBrew certified firmware v19)
[10.0.0.98:2016-11-13 12:38:24] Found Smarter Coffee (iBrew certified firmware v20)
[10.0.0.99:2016-11-13 12:38:24] Found iKettle 2.0 (iBrew certified firmware v19)

```
ip are at the beginning of the line (e.g.  10.0.0.3, 10.0.0.98...)
```
MacBook-Pro:iBrew Tristan$  ./ibrew info 10.0.0.99

  Starting please wait...

iKettle 2.0 (iBrew certified firmware v19)
```
now this should work...

```
./ibrew settings 10.0.0.98

  Starting please wait...

brew 3 cups of filter coffee and keep hotplate warm for 10 minutes
```

**Comment by DemianTinkiel** [comment]
The thing is that it doesn't find ANY machines
```
192.168.4.1:None$list
No coffee machine or kettle found
```
how can I force autodetect?

**Comment by Tristan79** [comment]
You can try:

* firewall blocking port 2081?
* Looking up the ip of the appliance in your dhpc server (usually you can find it in your internet)
* Clone again
* Make sure that your kettle/coffee machine is on the same network and _subnet_ as your pc and your phone.
* Reset appliance (ikettle is longer then 10 seconds button hold on base, coffee machine, eeuh I forgot which button but you can use the smarter app to do that to reset wifi) 
* Try connect with your wifi of your pc (if it has wifi) to the iKettle:?? or SmarterCoffee:?? wireless network and try if it works.
* reconnect to your wifi network (and if you are lucky and could connect with ibrew in direct mode, the command is `./ibrew join namewireless password`) else use your phone.

 It could be that your router is blocking utp broadcast messages (some do, so it never auto detects). Does the Smarter app autodetects it?

**Comment by Tristan79** [comment]
Think the biggest chance is a firewall blocking port 2081 or utp broadcast messages...

**Comment by klemmer** [comment]
Hello,
 I'm having the same issue. If I type
ibrew info 192.168.1.15
it says
2018-09-06 15:14:23,032 - DEBUG - [Errno 111] Connection refused
2018-09-06 15:14:23,032 - ERROR - [192.168.1.15] Could not connect to 192.168.1.15:2081

If I type
ibrew list
it says
No coffee machine or kettle found

I have tried ibrew from both a Raspberry Pi and a MacBook on the same 2.4GHz network as the coffee machine. Strangely:
 * Wireshark doesn't show any traffic to 192.168.1.15 when I do this.
 * Port Scan doesn't show any open ports on 192.168.1.15
 * I can brew coffee from both the Smarter app on my phone and IFTTT
I have a Netgear Orbi router. The Smarter app and IFTT work without any changes to it. Still, I tried:
 * Port Forwarding TCP/UDP 2000-3000 to 192.168.1.15
 * Setting 192.168.1.15 as the Default DMZ Server in WAN Setup
 * Checking 'Disable SIP ALG'
 * Disable Port Scan and DoS Protection
 * Respond to Ping on Internet Port
Even with all of these changes:
 * Port Scan does not list any open ports on 192.168.1.15
 * Wireshark does not list any network traffic on 192.168.1.15

Any suggestions on what might be causing this 'connection refused' from MacBook/Pi when the coffee machine works from Smarter and IFTTT?
