### ISSUE TITLE
iKettle 1.0

### ISSUE THREAD

**Issue by samsonrosen** [Tristan79/iBrew#23]
http://smarter.am/support-ikettle-1-0/

Would it be possible to support the original iKettle?

**Comment by Tristan79** [comment]
:-)

Without a remote kettle to test...  https://github.com/Tristan79/iBrew/blob/master/ibrewlegacy (still needs the rest of iBrew)
I did not integrate it into iBrew (maybe later, if it all works) but created a command line interface, I called it

```
./ibrewlegacy
```

I have NO idea if it works (ir correctly)... I used https://github.com/jerrosenberg/kettle-fake/projects which gives back some message replies, but I am not sure if the sim kettle is correct... neither do I know how many replies a command gives back (1, 2 or more???) you should test it...
The get status (the thing you want for homebridge) is kinda untested... the fake kettle does not send that... :-)

Also I have no idea if you need a pin (if you use the ios app), or what that does... nor did I implement the wifi commando's...

We can always do a remote session. Probably the easiest way to test stuff, and luckily the kettle does have a very simpel protocol...

But as you see, I already have a framework with all the messages implemented... :-)

**Comment by samsonrosen** [comment]
Hi Tristan!

Thanks for the fast reply - excited to see this could work and happy to donate. 

I've tried a couple of the commands and it looks good so far for example:

 ./ibrewlegacy heat 192.168.1.5

I do get an error when I try the status command:

`Church-Server:iBrew churchserver$ ./ibrewlegacy status 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Kettle status
Traceback (most recent call last):
  File "./ibrewlegacy", line 323, in <module>
    print "Received 1: " + decode_status(data[0:len(data)-1])
  File "./ibrewlegacy", line 109, in decode_status
    return decode_replyStatus(status)
  File "./ibrewlegacy", line 93, in decode_replyStatus
    if is_set(statusdata,0):
NameError: global name 'is_set' is not defined
Church-Server:iBrew churchserver$ 
`

Would you like to try and play with this remotely? I am happy to do this whenever. I could try and open the kettle up remotely, or open a TeamViewer session.

**Comment by samsonrosen** [comment]
`Church-Server:iBrew churchserver$ ./ibrewlegacy heat 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Start heating water
Received 1: Heating water
Received 2: 100ºC selected

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!
Church-Server:iBrew churchserver$ ./ibrewlegacy stop 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Stop heating water
Received 1: Ready

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!`

**Comment by Tristan79** [comment]
I added the status message to the fake kettle and fix some code... it should work now... status

**Comment by samsonrosen** [comment]
Hey! I did a gitpull and status definitely seems to do more. 

It only gives you the status if you've selected Boil or another command etc. I presume that's okay?

`Church-Server:iBrew` churchserver$ /Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Kettle status
Received 1: 

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!
Church-Server:iBrew churchserver$ clear

Church-Server:iBrew churchserver$ /Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Kettle status
Received 1: 

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!
Church-Server:iBrew churchserver$ /Users/churchserver/iBrew/ibrewlegacy heat 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Start heating water
Received 1: Heating water
Received 2: 100ºC selected
^[[A
iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!
Church-Server:iBrew churchserver$ /Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Kettle status
Received 1: Heating water 100ºC selected

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used!
Church-Server:iBrew churchserver$ /Users/churchserver/iBrew/ibrewlegacy stop 192.168.1.5
iBrew: Legacy iKettle Interface
iBrew: Intermezzo © 2016 Tristan (@monkeycat.nl)
iBrew: LICENSING AGREEMENT accepted by LICENSEE Sam Rosen

Please DONATE! Food, jokes, hugs and fun toys!

Contribute any discoveries on https://github.com/Tristan79/iBrew/issues

This is untested code. Please report your findings!!! 

Sending: Stop heating water
Received 1: Ready

iBrew: Did you see reply messages? Please report on https://github.com/Tristan79/iBrew/issues, which reply messages are received and which command is used``

**Comment by Tristan79** [comment]
It should said ready.... i think :-) Next weekend I have more time to look at the code. 

But for homebridge. You could try adding this to your configuration:

```
 "platforms": [{
        "platform": "cmdSwitch2",
        "switches": [{
            "name": "iKettle",
            "on_cmd": "/Users/churchserver/iBrew/ibrewlegacy heat 192.168.1.5",
            "off_cmd": "/Users/churchserver/iBrew/ibrewlegacy stop 192.168.1.5",
            "state_cmd": "/Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5 | grep 'Heating'"
        }]

    }]

```

**Comment by samsonrosen** [comment]
Yeah - this looks like what I've added to my config file. I mimicked what you'd posted for iKettle 2.0

This is amazing though, its great you had already done the work (for me)! 

Thanks for you help! Let me know if you do want to test anything out.

Thanks,

Sam

**Comment by Tristan79** [comment]
Just you know! luisiam introduced status polling for the homebridge cmdswitch2 a couple of hours ago :-) This means (hopefully) a correct in sync status in homekit.

https://github.com/luisiam/homebridge-cmdswitch2

**Comment by samsonrosen** [comment]
Nice one! I presume the code stays the same and I just need to update both instead.

**Comment by Tristan79** [comment]
You have to update/git pull https://github.com/luisiam/homebridge-cmdswitch2

and add

```
        "polling": true,
        "interval": 1,
```

to your json to enable it according to https://github.com/luisiam/homebridge-cmdswitch2 :-)

**Comment by samsonrosen** [comment]
Hello,

I have updated both cmdswitch2 and iBrew, and added the above information to my config file. The Kettle still works, but the logs look like this after using HomeKit/Home:

Church-Server:~ churchserver$ homebridge 
[11/25/2016, 5:13:15 PM] Loaded plugin: homebridge-cmdswitch2
[11/25/2016, 5:13:15 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[11/25/2016, 5:13:15 PM] ---
[11/25/2016, 5:13:15 PM] Loaded plugin: homebridge-rm-mini3
[11/25/2016, 5:13:15 PM] Registering accessory 'homebridge-rm-mini3.RM mini3'
[11/25/2016, 5:13:15 PM] ---
[11/25/2016, 5:13:15 PM] Loaded plugin: homebridge-wemo
[11/25/2016, 5:13:15 PM] Registering accessory 'homebridge-wemo.WeMo'
[11/25/2016, 5:13:15 PM] ---
[11/25/2016, 5:13:15 PM] Loaded config.json with 1 accessories and 1 platforms.
[11/25/2016, 5:13:15 PM] ---
[11/25/2016, 5:13:15 PM] Loading 1 platforms...
[11/25/2016, 5:13:15 PM] Initializing cmdSwitch2 platform...
[11/25/2016, 5:13:15 PM] Loading 1 accessories...
[11/25/2016, 5:13:15 PM] [Bedroom Light] Initializing WeMo accessory...
[11/25/2016, 5:13:15 PM] [Bedroom Light] Searching for WeMo device with exact name 'WeMo Switch'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
`[11/25/2016,` 5:13:15 PM] Homebridge is running on port 51826.
[11/25/2016, 5:13:15 PM] [Bedroom Light] Found 'WeMo Switch' device at 192.168.1.227
[11/25/2016, 5:13:37 PM] Kettle is off.
[11/25/2016, 5:13:37 PM] [Bedroom Light] Getting power state on the 'WeMo Switch'...
[11/25/2016, 5:13:37 PM] [Bedroom Light] Power state for the 'WeMo Switch' is 0
[11/25/2016, 5:13:39 PM] Kettle is on.
[11/25/2016, 5:13:39 PM] Turning on Kettle took too long, assuming success.
[11/25/2016, 5:13:40 PM] Kettle is turned on.
[11/25/2016, 5:13:41 PM] Kettle is on.
[11/25/2016, 5:13:43 PM] Kettle is off.
[11/25/2016, 5:13:43 PM] Kettle is on.
[11/25/2016, 5:13:45 PM] Kettle is off.
[11/25/2016, 5:13:47 PM] Kettle is on.
[11/25/2016, 5:13:47 PM] Kettle is off.
[11/25/2016, 5:13:49 PM] Kettle is on.
[11/25/2016, 5:13:50 PM] Kettle is off.
[11/25/2016, 5:13:51 PM] Kettle is on.
[11/25/2016, 5:13:52 PM] Kettle is off.
[11/25/2016, 5:13:53 PM] Kettle is on.
[11/25/2016, 5:13:54 PM] Kettle is off.
[11/25/2016, 5:13:55 PM] Kettle is on.
[11/25/2016, 5:14:16 PM] Kettle is off.
[11/25/2016, 5:14:16 PM] Kettle is on.
[11/25/2016, 5:14:18 PM] Kettle is off.
[11/25/2016, 5:14:19 PM] Kettle is on.
[11/25/2016, 5:14:20 PM] Kettle is off.
[11/25/2016, 5:14:21 PM] Kettle is on.
[11/25/2016, 5:14:22 PM] Kettle is off.
[11/25/2016, 5:14:23 PM] Kettle is on.
[11/25/2016, 5:14:24 PM] Kettle is off.
[11/25/2016, 5:14:25 PM] Kettle is on.
[11/25/2016, 5:14:26 PM] Kettle is off.
[11/25/2016, 5:14:27 PM] Kettle is on.
[11/25/2016, 5:14:48 PM] Kettle is off.
[11/25/2016, 5:14:48 PM] Kettle is on.
[11/25/2016, 5:14:50 PM] Kettle is off.
[11/25/2016, 5:14:51 PM] Kettle is on.
[11/25/2016, 5:14:52 PM] Kettle is off.
[11/25/2016, 5:14:54 PM] Kettle is on.
[11/25/2016, 5:14:54 PM] Kettle is off.
[11/25/2016, 5:14:56 PM] Kettle is on.
[11/25/2016, 5:14:56 PM] Kettle is off.
[11/25/2016, 5:14:57 PM] Kettle is on.
[11/25/2016, 5:15:18 PM] Kettle is off.
[11/25/2016, 5:15:18 PM] Kettle is on.
[11/25/2016, 5:15:20 PM] Kettle is off.
[11/25/2016, 5:15:22 PM] Kettle is on.
[11/25/2016, 5:15:22 PM] Kettle is off.
[11/25/2016, 5:15:24 PM] Kettle is on.
[11/25/2016, 5:15:24 PM] Kettle is off.
[11/25/2016, 5:15:26 PM] Kettle is on.
[11/25/2016, 5:15:26 PM] Kettle is off.
[11/25/2016, 5:15:28 PM] Kettle is on.
[11/25/2016, 5:15:50 PM] Kettle is off.
[11/25/2016, 5:15:50 PM] Kettle is on.
[11/25/2016, 5:15:52 PM] Kettle is off.``

[config.json.zip](https://github.com/Tristan79/iBrew/files/613677/config.json.zip)

**Comment by Tristan79** [comment]
Ok, well I expanded the fake ikettle to test it... for me, it's running fine... But, yeah, it could be that the a real ikettle is sending other status messages... or other bugs... :-)

To please update ibrew and run the new legacy monitor for a while, while doing your homekit test... :-)
and post the log...

So please run... in another terminal window
./ibrewlegacymonitor.sh  192.168.1.5

it will create ibrewlegacymonitor.log file and monitors what is going on...

press ctrl-c a couple of times to quit...

and if this won't work then I have to investigate with a real kettle...

**Comment by samsonrosen** [comment]
I’m probably becoming a bit of a nightmare now!

I git pulled, but it gave some conflicts and now all I get is this repeatedly:

                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/25/2016, 9:13:49 PM] Homebridge is running on port 51826.
[11/25/2016, 9:13:49 PM] Failed to determine Kettle state.
[11/25/2016, 9:13:49 PM]   File "/Users/churchserver/iBrew/ibrewlegacy", line 264
    <<<<<<< HEAD
     ^
IndentationError: expected an indented block

[11/25/2016, 9:13:50 PM] Failed to determine Kettle state.
[11/25/2016, 9:13:50 PM]   File "/Users/churchserver/iBrew/ibrewlegacy", line 264
    <<<<<<< HEAD

**Comment by Tristan79** [comment]
Git merge conflict, funny :-)

Delete the iBrew folder and clone a brand new version to the same location. That would solve the merge conflics...


```
cd /Users/churchserver/
rm -rf ./iBrew/
git clone https://github.com/Tristan79/iBrew.git
```
