### ISSUE TITLE
Watersensor Puzzle!

### ISSUE THREAD

**Issue by cismarine** [Tristan79/iBrew#25]
Hi I am new to the iBrew project. Just tried to set it up with home bridge on OSX and getting some errors.
Anyone can help?

[12/1/2016, 6:18:25 PM] Failed to determine iKettle 2 state.
[12/1/2016, 6:18:25 PM] /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/iBrew/ibrew': [Errno 2] No such file or directory

**Comment by Tristan79** [comment]
It can not find ibrew in path /iBrew/ibrew. You probably have ibrew in your user folder?

I never tested it with the dmg package if that is what you are using, and its a couple commits behind... so please use git or use the https://github.com/Tristan79/iBrew/archive/master.zip zip file.

Just unzip or git it in the folder of your choice and use the full path in the homebridge config file. 

ie. I have it unzipped in  `/Users/Tristan/iBrew`

the path in the homebridge config file will be `/Users/Tristan/iBrew/ibrew`

Anyway hope that helps :-)

**Comment by cismarine** [comment]
Tristan,

Thank you for your quick support.

Bart

**Comment by cismarine** [comment]
Tristan,

I have followed your email, but now getting this:

Last login: Thu Dec  1 22:07:22 on ttys002
/Users/cis/iBrew/ibrew ; exit;
server:~ cis$ /Users/cis/iBrew/ibrew ; exit;
Traceback (most recent call last):
  File "/Users/cis/iBrew/ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/cis/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/cis/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Tristan79** [comment]
Yes you are missing python packages, run in a terminal in the iBrew folder...

pip install -q -r requirements.txt

**Comment by cismarine** [comment]
Thanks,

Got it running without error now.
One last question... how can I run web interface now?

**Comment by Tristan79** [comment]
you can also download the dmg package,... i updated it to my latest.

If you run the package, it will create a symlink from where you run it in

 `/usr/local/bin/ibrew`

or run in the iBrew folder:

pip install -q -r distro/mac/requirements-mac.txt

then you can run

./ibrewui

I haven't fininshed it :-) the rest api is working (the backend) 

...but the frontend, is only partly functional... I planned to finish at the end of december, I never wrote javascript or css/html before... I still have to play with it... :-) especially css is a pain in the... all those different resolutions used by phones, tablets and desktops... :-)

**Comment by Tristan79** [comment]
And I totally got blindsided by the *bling* of the nice icon...
You can always run the web interface with

`ibrew web`

**Comment by cismarine** [comment]
Tristan, 
It was going all good, but now getting following errors:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file SmarterInterface.py, line 1009
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file SmarterInterface.py, line 1010
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file SmarterInterface.py, line 1011
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file SmarterInterface.py, line 50
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file SmarterInterface.py, line 51
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file iBrewConsole.py, line 501
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 32] Broken pipe
Logged from file iBrewConsole.py, line 502

**Comment by Tristan79** [comment]
Really weird, try removing ~/Library/Application Support/iBrew/

(in terminal use: `rm -rf ~/Library/Application Support/iBrew/`)

and download the dmg package which has all the python precompiled within https://dl.dropboxusercontent.com/u/12474226/iBrew.dmg
or try the updated https://github.com/Tristan79/iBrew/archive/master.zip

And report back what works :-)

**Comment by cismarine** [comment]
Hi Tristan,

I have question for you…
do you know how does water level correspond with liters or ml?
Thanks for iBrew! 

Bart

**Comment by Tristan79** [comment]
Well, I do not know...

It is a weight sensor.

The kettle has a calibration base value, which should be always the same, but the weight of the kettle is not in balance and the weight sensor is not in the middle... Thus that's why the ask are you left or right handed...

Then you could calibrate ml using the weight sensor, (hoping the kettle is put on base on the same place)... but depending on the temperature... the weight sensor is higher or lower with the same amount of water...  I have not figured out the formula or relations... and neither did smarter, their cups indication is also highly inaccurate...

if you have any idea... :-)

there is the watersensorraw (around 2000), calibrationbase (around 1000) and temperature... 
and the amount of water you put in ;-) with the calibrtion base depending that you did it with a empty kettle and you put the kettle back the same way every measurement...

the watersensor i show in ibrew is the raw sensor minus the base...

Anyway its a puzzle!

**Comment by cismarine** [comment]
Hi,

I have tried to calibrate it filling with small increments of water (100ml) from empty to 2L… what a job (-:
unfortunately the results are all over the place, so I am leaving it for now. 
I have rough estimate of level in crestron and not going to spend more time on it.
Thanks for your help along the way.
Got one little thing that I picked up in ibrew:
I moved it to raspberry and getting message when starting it up:
-DEBUG- Unable to auto-detect the network interface
-INFO- iBrew Could not connect to [192.168.4.1]

I am not sure where is that ip address comping from as my network range is different.

Bart

**Comment by Tristan79** [comment]
Ah, yeah... I presume you do not have wireless (enabled) on your pi? I looked and it looks like no error checking around that... Fixed in new code... :-)

**Comment by cismarine** [comment]
Hi,

My Pi is on LAN. No wireless interface at all.


Regards,
Mit freundlichen Grüßen,

Bart J. Podkowka

cismarine ltd 

+34 616273563     (Spain)
+44 7482 569628‬  (UK)
‭+33 640616991‬     (Monaco)
+49 15157881751 (Germany)

Marine Control Systems • IT • Communication • Surveys

cismarine ltd. registered in England. 
company number 10129642 
vat: GB 248 2438 93
71-75 Shelton Street, Covent Garden, London WC2H 9JQ, England

**Comment by Tristan79** [comment]
It tried to detect the direct wireless connections... never tested it
without wireless...  should work :-) Let me know if it isn't. Then I fix it
when I get back home.
