### ISSUE TITLE
Samsung Smartthings Integration

### ISSUE THREAD

**Issue by jonbur** [Tristan79/iBrew#30]
Hi,

First of all, thanks for the great project.

I am in the process of writing a Samsung Smartthings integration with iBrew. 

So far I have a simple Device Type (which is the Smartthings name for the interface code for a particular device) - see https://github.com/jonbur/smartthings/blob/master/iBrew.groovy - which uses the iBrew JSON REST API.

The device is functional (although the kettle IP is hard-coded - to fix!) and provides simple on/off control and feedback on temperature.

However, at present, the device status only updates when the 'refresh' button is clicked in Smartthings. I am keen to avoid polling, as polling in Smartthings is a bad idea.

I am wondering if the JSON REST API could be extended to support a 'SUBSCRIBE' method and a HTTP callback whenever there is a change in device status? 

It looks like adding SUBSCRIBE should be relatively straight forward with tornado (and code to track callback endpoints), but I am struggling to understand how device state is tracked in iBrew (__monitor_device?) and where the 'right' place to process call backs would be?

A callback capability would likely be useful for other Smarthome system integrations too...

Cheers

Jon

**Comment by Tristan79** [comment]
The right place to add it would be:


__decode_KettleStatus()

__decode_CoffeeStatus()


where all the status updated are (or any other __decode_???() you need for
advance functionality)


with the monitor on it fires every second (you could skip temperature
changes and waterlevel changes if smarthome can not handle that and fire
only when things change...)

and if you miss something in the json rest, please tell or add :-)

**Comment by jonbur** [comment]
Thanks, I will take a look and come back as needed.

**Comment by Tristan79** [comment]
For questions where stuff is in the code and little bug fixes I have time ;-)

**Comment by jonbur** [comment]
So looks like I have fallen at the first hurdle - how do I start both the webserver and monitor at the same time? command 'ibrew monitor {kettle ip}' works and 'ibrew web' works, but combinations of the two don't....

Also, ctrl+c does not cleanly close 'ibrew web' - i get: 

[192.168.1.184:2016-12-12 19:55:10] Found iKettle 2.0 (iBrew certified firmware v19)
2016-12-12 19:55:11,826 - INFO - iBrew: Stopped Web Interface & REST API on port 2080

But then hangs (a further ctrl+c has no effect) and I have to kill the process with SIGKILL

**Comment by Tristan79** [comment]
Yeah I know, I have a lot of problems with threads not ending... its on my to do list together with better logging :-) I got sick in the middle of the testing and building the web front end stage... that why it called ibrew intermezzo at the moment ;-)

`./ibrew dump web ` should give you both terminal monitoring and a web interface.

**Comment by jonbur** [comment]
Thanks, got it!

**Comment by Tristan79** [comment]
Seems the rest api was a little out of date and was missing pieces... I added them, most stuff should work (i still have to add the error handling)... anyway, you should update before you tinker :-)

**Comment by Tristan79** [comment]
Checkout: http://yourip:2080/info/api for the updated examples :-)

**Comment by jonbur** [comment]
Thanks  very much - I will pull the update later and merge back the changes (I have got the subscription manager mostly working)

**Comment by Tristan79** [comment]
I will change the decode in the smarter so you can see where the triggers are ;-)

**Comment by Tristan79** [comment]
You should check out this branch...

https://github.com/Tristan79/iBrew/tree/eventtriggers

it got all the trigger point i could find (untested all ;-)

check out https://github.com/Tristan79/iBrew/blob/eventtriggers/smarter/SmarterInterface.py#L2314

    def actionAdd(self,group,trigger,sensorID,action)
    def actionDelete(self,group,trigger)

    def action(self,trigger,old,new)

still need to fill it up yourself, but at least you now have a centralised event system ;-)

(how to deal with boolean (on,1,true,True,On????) will be an issue... ;-)

Anyway, hope i did not make any paste & cut mistakes ;-) barebone! enjoy! it now print the trigger in def action ;-)

**Comment by jonbur** [comment]
Thanks - will have a look when I am next back in front of dev machine

**Comment by jonbur** [comment]
...train delayed, so had a chance to look :-)

If I have this correctly, you intend the 'actions' dictionary to be used as the structure to hold all event handlers, with actionAdd and actionDelete used to add / delete individual event handlers from the dictionary (with a tuple added for each, indexed with the trigger name). Is that correct?

Do you have any view on persistence of the structure between process restarts? Is anything else persisted, or all in memory?

I see that action() is called by the various different decode methods and understand the general intention of the commented out code from ln2401. 

What is the intention of 'Group'?

Thanks

**Comment by Tristan79** [comment]
But yeah that is correct, but you can use any structure you like which is more appropiate, I only sketch that part :-)

I though about the group being the identifier Like "domoticz", such that you can add or delete stuff from one subscription and do not bother the rest...

i have second thoughts about sensorid, sensorid is an identifier used by the controller e.g. domoticz has a number to identify which sensor to update...  but then again this also could be in the url already.... so maybe that is double... so lets remove that.

so yeah i suggest per trigger a set of actions which consists of tupples of ids (group) and their action (either url or command).

```
 {("iBrew","/home/pi/iBrew/trigger.sh $O $N"),("Domoticz","http://smarthome.local/controller/update?sensor=454&value=$N")},("MTTQ","D:\coding\iBrew\trigger.bat $O $N"),("OpenHAB","http://smarthome.local/controller/update?sensor=RoomTemp&value=$N")}
```
Have not thought about persistence :-), have though about that the first trigger is always wrong, cuz of the default state... but then again most controllers could use a status update when powered off...
have to think about that...

further persistence of the actions will come in the config "194.168.4.1.conf" files with the stats i think, probably end up adding that to ibrewweb.py :-) since i did not want it in smarterinterface.py :-)

But then again, it is only a sketch!  
Except now you know which triggers there are, and have a central point (def action) to do stuff with it :-)

**Comment by jonbur** [comment]
Great, thanks - all understood. Will have a look tomorrow.

**Comment by Tristan79** [comment]
Just run` ibrew console` once to create a config file.
You can play with it if you use the following config add it to `ibrew.conf`

```
[10.0.0.99.triggers]
groups = Domoticz,OpenHAB

[10.0.0.99.triggers.Domoticz]
active = False
state = On
busy = http://www.google.com/$N&$O
defaulttemperature = 
defaultformulatemperature = 
defaultkeepwarm = 
base = 
keepwarm = http://www.google.com/$N&$O
heater = 
formulacooling = http://www.google.com/$N&$O
temperature = 
watersensor = 
onbase = http://www.google.com/$N&$O
unknown = 

[10.0.0.99.triggers.OpenHAB]
active = True
state = 1
busy = /e/x
defaulttemperature = 
defaultformulatemperature = 
defaultkeepwarm = 
base = 
keepwarm = /e/x
heater = 
formulacooling = /e/x
temperature = 
watersensor = 
onbase = /e/x
unknown = 

```

active = True  <-- if it fires
state = 1 <-- On,on,ON,ENABLED,Enabled...,1,0,Off  how you write bools to controller..

command line add/delete not finished :-), also local command execution not tested...

```
ibrew trigger add
ibrew trigger delete
```
does not work... that for after supper...  all alpha... :-)


ibrew triggers
ibrew states

Shows a list of triggers
./ibrew trigger 10.0.0.99

Shows list of groups
./ibrew trigger groups 10.0.0.9

anyway

```
  Triggers
    trigger add [group] [trigger] [action] add trigger to a group
    trigger delete [group] (trigger) delete trigger or group triggers
    trigger groups         show list of groups
    trigger [group]        show triggers of group
    trigger                show all triggers
    trigger [group] [bool] enabled/disable trigger group
    trigger [group] state [bool] set group state output
```

**Comment by Tristan79** [comment]
You now can add (or modify) trigger with 

`./ibrew trigger add Domos Temperature http://sss/$N&$O 10.0.0.99`

and check them out with ibrew trigger and ibrew trigger groups

**Comment by jonbur** [comment]
Thanks - looks good. It will likely be next week when I am done travelling when I get to look at this :-)

**Comment by jonbur** [comment]
So, had a quick look :-)

(Hadn't realised you had merged the branch back to main)

Calling ibrew web I get:


```
2016-12-14 21:08:09,316 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 47, in new
    r = fn(*args, **kwargs)
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 2524, in __read_triggers
    os.makedirs(self.settingsPath)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

2016-12-14 21:08:09,317 - DEBUG - [Errno 2] No such file or directory: ''
2016-12-14 21:08:09,318 - DEBUG - [Errno 2] No such file or directory: ''
2016-12-14 21:08:09,319 - INFO - iBrew: Failed to run Web Interface & REST API on port 2080
```

Sorry, not got time to look at it further - looks to be an issue creating the conf file

**Comment by Tristan79** [comment]
Yeah, I did cuz of all the other bug fixes...  and ofcourse there where more bugs to squash... as you notice, I fixed that too. And there are probably more to come ;-) Never ending stream of ants walking to the code messing everything up ;-)

The backbone is ready, you can add, delete triggers...  and they will fire urls or scripts :-)
I can see graphs now of my temperature in domoticz... ;-) I tested it with a clean install on a pi,,

./brew dump events web

It probably needs other sensors like text sensors (status) or smooth out water and temperature sensor, like it has in the monitor... :-)

Looking forward to the subscription part!

**Comment by jonbur** [comment]
Thanks, that's fixed the missing file bug - starts cleanly with dump and web

I am now out of the country for a few days - likely next week when I get chance to modify the subscription handler to call the new trigger system

Cheers

**Comment by Tristan79** [comment]
Well if you come back from you're far away travels...

...the new _ibrew_ is awaiting  :-o

it triggers, already added smoothers to the water sensor and temperature sensors, such that is does not trigger that much, fixed webserver and relay hanging so it actually quits :-)...

**Comment by jonbur** [comment]
Awesome :-) 

I'm back in UK on Monday, hopefully get to merge back the subscription code then

**Comment by jonbur** [comment]
So managed to have a quick play over SSH

Have got the basics of the subscription handler added back

However, think I have hit a bug in the events system

When I start 'ibrew dump events web' I get:

`2016-12-17 15:29:16,359 - INFO - [192.168.4.1] Simulation Running
[192.168.1.178:2016-12-17 15:29:18] Found iKettle 2.0 (iBrew certified firmware v19)
2016-12-17 15:29:18,312 - INFO - [192.168.1.178] Adding Web Device
[192.168.1.178:2016-12-17 15:29:18] Connecting appliance
[192.168.1.178:2016-12-17 15:29:18] Message Send     [Get appliance info] [647e]
2016-12-17 15:29:18,416 - INFO - [192.168.1.178] Monitor Running
[192.168.1.178:2016-12-17 15:29:18] Message Received [Appliance info] [6501137e]
iKettle 2.0 (iBrew certified firmware v19)
[192.168.1.178:2016-12-17 15:29:18] Message Send     [Get default kettle user settings] [2e7e]
2016-12-17 15:29:18,567 - INFO - [192.168.1.178] Simulation Running
2016-12-17 15:29:18,759 - DEBUG - JB: running trigger handler
[192.168.1.178:2016-12-17 15:29:18] Disconnecting iKettle 2.0
None

Could not read message not connected
2016-12-17 15:29:18,766 - INFO - [192.168.1.178] Monitor Stopped
iBrew: Cannot run bonjour server! Maybe some packages need to be installed?
2016-12-17 15:29:18,873 - INFO - iBrew: Starting Web Interface & REST API on port 2080. Press ctrl-c to stop
iBrew: Press ctrl-c to stop
[192.168.1.178:2016-12-17 15:29:36] Found iKettle 2.0 (iBrew certified firmware v19)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pi/iBrew/iBrewWeb.py", line 1026, in autoconnect
    if self.reconnect_count[ip] < 7:
KeyError: '192.168.1.178'
`

Am I doing something stupid!?

**Comment by jonbur** [comment]
(FYI ' DEBUG - JB: running trigger handler' is just added at the top of the __trigger method so I could check it was being called)

**Comment by Tristan79** [comment]
Probably not, probably a bug or a typo on my end. If you forked a repo and synced it I will check it out tomorrow...  :-) I am currently hacking in "iKettle bridge 1.0 <-> 2.0"
emulation of  "iKettle 2.0 -> iKettle Legacy"  (first part barely functional) or "iKettle Legacy -> iKettle 2.0" emulation.  

Make your iKettle Legacy an iKettle 2.0 or show your iKettle 2.0 as a iKettle Legacy! Coming soon! Near you on GitHub :-)

**Comment by jonbur** [comment]
Yes, this is in a fork syned to your latest master

Thanks

**Comment by Tristan79** [comment]
Uhm, I think you have to git push or sync it with the online repo, code is not showing up :-)

**Comment by jonbur** [comment]
Ah, sorry, no I meant that my fork is locally synced to your repo, not the other way round :-)
 
(At least it was 24 hours ago!)

Anyway, have pushed work in progress to https://github.com/jonbur/iBrew

I don't think the bug touches these changes anyway - just calling 'ibrew dump events web' on your master branch gives me the same fault

**Comment by jonbur** [comment]
Also, I have found another bug I think that is triggered in the new subscription handler

When I first call "client.triggerAdd("SmartThings", "Temperature","http://google.com")" from within iBrewWeb.py (new subscription handler method - see line 810)

I get the following:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/pi/iBrew/iBrewWeb.py", line 810, in subscribe
    client.triggerAdd("SmartThings", "Temperature","http://google.com")
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 2604, in triggerAdd
    self.triggerSet(group,trigger.upper(),action)
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 2712, in triggerSet
    if self.triggersKettle[id][i][0] == group:
IndexError: list index out of range
2016-12-19 16:40:05,353 - ERROR - 500 SUBSCRIBE /api/192.168.1.178/subscribe (192.168.1.3) 25.35ms
[192.168.1.178:2016-12-19 16:40:07] Me

There is some weirdness with the tracking of groups. If I call 'ibrew trigger' nothing is returned, yet various entries are shown in /etc/iBrew/iBrew.conf and _isGroup(self,group) has entries in 'group'

If I clean up /etc/iBrew/iBrew.conf and restart the process I don't encounter the error... I think it's not loading from .conf correctly?

Many thanks

**Comment by Tristan79** [comment]
I did my best :-) Please delete the config file, it probably has a wrong encoding (and stuff)... and it should now work cross platform.

Do not know if the rest api add triggers works ok with all urls but...  

You can check in the iBrewWeb examples on how to add/delete/show triggers handlers using method "get". You wanted a method "subscribe". You can use those as a bases. I am too unfamiliar with http stuff :-) everything is method "get" for me ;-) I still want to add an admin section with password and apikey support... but how that works, I have not figured out yet, soo much to discover ;-)

Also struggling with CSS, man that is some weird funky stuff!

And i fixed (i hope i did, the reading and writing of triggers), there were some bugs there....

Anyway please test it...

**Comment by jonbur** [comment]
Thanks Tristan

So I have finally got SmartThings subscribing to events and processing updates properly (just for temperature updates at the min)...  It uses some undocumented parts of SmartThings which has been painful to work out.

At the min I have hacked in a SmartThings specific trigger handler (as it turns out SmartThings hub will only deal with a POST). See https://github.com/jonbur/iBrew/ - new  SmarterInterface.py and iBrewWeb.py

I am sure I am being obtuse, but what is the correct way to match on trigger type (Temperature etc.) in the Trigger handler? I am using Smarter.triggersKettle[triggerID][0] == "Temperature" etc. (line 3662), but is there a dictionary or enum I should be using instead? 

Also, what trigger is fired when the kettle status changes ('ready', 'heating' etc.)?

Thanks again and happy holidays

**Comment by Tristan79** [comment]
I can make the trigger system deal with post and get, it just another field. I think ;-) I will have a look

**Comment by Tristan79** [comment]
Ah, 

Smarter.triggersKettle[triggerID][0]
same as
Smarter.triggerName(triggerID)

you should probably not pull at the moment, i broke the trigger system... hopefully in an hour + 4 hours sleep, I need a nap :-)

you have any links on how the smartthings communicated?

So as I understand you fill in somewhere in the SmartThing the ip (or link) to iBrew? 
Using https://github.com/jonbur/smartthings/blob/master/iBrew.groovy?

**Comment by jonbur** [comment]
Ah, ok - I thought Smarter.triggerName(triggerID) returned the URL being called, whilst Smarter.triggersKettle[triggerID][0] gave the triggering event... Will look again

For general info on Smart Things see http://docs.smartthings.com/en/latest/device-type-developers-guide/

Basically, a device handler is the bit of code that interface the third-party device into the SmartThings universe. iBrew.groovy is the device handler (very crude at this stage) that does this for iBrew. Yes, you set the IP, port no. and MAC address in a configuration screen for the device handler. 

Basically, the device handler calls new Subscribe method I have added to the iBrewWeb and sets up the call backs. When the trigger fires, the new method POSTs JSON at the call back URL given in the subscribe. The call backs then get passed to the Parse() method in the device handler automagically by SmartThings (this is what I have been fighting with - the undocumented thing is that to make this work you have to use the MAC as the unique identifier. Anyway...)

The parser in the event handler expects a blob of JSON with the trigger values. I can make this cope with pretty much any properly formatted JSON. 

Does that make sense?
Thanks

**Comment by Tristan79** [comment]
Yes I understand. Except for the mac part. Do you want iBrew to generate one like an api key?, or is it a real mac address? Anyway...

url = self.triggerGet(group,Smarter.triggerName(triggerID))
nameoftrigger = Smarter.triggerName(triggerID) # LIKE ONBASE, WATERSENSOR see ./ibrew triggers

i should have classified it, and choose better names... i should designed the code a lot better at hindsight, but this whole project is a total hack, me trying out stuff :-)

Going to fix the trigger soon... i think its the last type bug I have to find. Next step soon is fully emulating a iKettle 1 with and iKettle 2 and visa versa... just because I can :-)

After I played finish playing with my [weigth scale](https://github.com/Tristan79/BS440) and the
[plant sensor](https://github.com/open-homeautomation/miflora) :-) [push script](http://domoticz.com/forum/viewtopic.php?f=56&t=13306&hilit=mi+flora&start=20#p105255)

**Comment by Tristan79** [comment]
Also, in the lastes version working... (master is fixed soon, I made a type somewhere and my error handling system in a correct way, is actually almost non existent :-( :-) 

[This release](https://github.com/Tristan79/iBrew/tree/807edd10cf0d285aa29af9e755df610283dcc9e0) has a working

/api/raw/TRIGGERNAME/

which return the raw value (integer,string) and nothing else. Its easier then processing json i think.

**Comment by jonbur** [comment]
The other project look cool :-)

I have now got the device handler / iBrew branch to the point that SmartThings stays in sync with temperature and heating/ready status - essentially this was what I was shooting for! The fork is up to date with this code, although it needs a *lot* of tidying up and some error handling!!

So, the MAC part is due to a limitation/feature(!) in the SmartThings system. In order for the global dispatcher to know which Device Handler to route the incoming POST to, it has to match on something. Usually, this is the IP and Port number tuple. This means that a normal response to a HTTP GET from the SmartThings hub from a server gets routed OK:

Hub -> HTTP Get -> Server
Server -> HTTP response -> Hub -> Global Dispatcher -> Correct device handler based on IP:Port of the server

However, when there is an asynchronous call back, as in this case, the originating port number is some random high-number port, not the port the webserver process in bound to. Therefore, the global dispatcher on the hub does not now which device handler to send the incoming POST to, so our parser never gets round this.

In order to avoid this problem, SmartThings provides the feature to use the MAC of the sending server as the key in the dispatcher. In this way, it does not matter what IP:Port combination the POST is sent from on the server, it gets routed to the correct device handler. Therefore, in the device handler config I have added a key for the real MAC of the iBrew server. It may be possible to do a real-time lookup on SmartThings effectively look in the ARP table), but I have not worked this out yet.

I don't think iBrew needs to care about this at all - just a limitation of SmartThings :-)

Incidentally, the above is just what I have been able to work out by experimentation - this is not officially documented :-(

As regards the raw output option, that may well be useful. At the min, the device handler I have written has a refresh method that calls /api/ip/status and parses the full json response, which is efficient in that use case as there is only one server call/response

Just so I have this clear, I have added triggers for kettleheater = true and kettlebusy = false to trap the kettle starting and stopping heating. Are there any other states here I am missing?

Cheers man :-)

**Comment by Tristan79** [comment]
Fixed.. stuff should work now... you can check out the live rest api (including raw) at

http://yourip:2080/info/api

**Comment by Tristan79** [comment]
Probably want kettle  ONBASE

its nice to know if the kettle is present... you know a warning from the
night time scene, which tells you to put the kettle back...

and you can add FORMULACOOLING,KETTLEHEATER and KEEPWARM as extra sensors,
nice to know what the kettle is doing besides busy...  btw:

busy = formulacooling or kettleheater.

The water sensor is kinda useless at the moment, except vague indication,
its a essentially a weight sensor... it has a calibration base but if you
put the kettle on differently, due to the kettle imbalanced weight
distribution (that why they ask left, or right sides handle), also it rises
when the temperature rises...  so have not figured out how to get from a
raw value to a x cups left or something usefull... but the smart app does
also a poor job... :-) if you have any ideas on interpreting the
watersensor let me know..

I would do: temperature, onbase, busy, waterlevel, and as extra the 3
states kettleheater, keepwarm, formulacooling.
