### ISSUE TITLE
MAC xOS 10 Homebridge failed to determine Smarter Coffee state

### ISSUE THREAD

**Issue by asharun** [Tristan79/iBrew#40]
Hi Tristan79,

First can I say you have done a great job in iBrew really impressed, must have been a pig to set up.

I have got the Web interface working, and in Homebridge i have Nest and Smartthings working fine, however i'm having trouble getting the iBrew link to work. I am getting the below when I run homebridge, I know its prob something really simple but if you have any ideas I'd be much appriciated.

Failed to determine Smarter Coffee state.
[12/20/2016, 10:56:38 AM] Traceback (most recent call last):
  File "/Users/grahamduke/iBrew/ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/grahamduke/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/grahamduke/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

Many thanks

Graham

**Comment by Tristan79** [comment]
```
cd /Users/grahamduke/iBrew/
make setup
```

it will install the missing packages... :-)

**Comment by Tristan79** [comment]
and if you do not have make installed (windows, some linux systems)

```
cd /Users/grahamduke/iBrew/
pip install -q -r requirements.txt
```

which does the same.

**Comment by asharun** [comment]
Hi Tristan79,

thanks for getting back to me so quickly.  I've tried both the above but am still getting the same issue.  any ideas?

Cheers

Graham

**Comment by asharun** [comment]
Not sure if this helps but this is what i get when i run homebridge

Grahams-Mac-mini:iBrew grahamduke$ homebridge
[12/20/2016, 4:03:10 PM] Loaded plugin: homebridge-cmdswitch2
[12/20/2016, 4:03:10 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[12/20/2016, 4:03:10 PM] ---
[12/20/2016, 4:03:14 PM] Loaded plugin: homebridge-nest
[12/20/2016, 4:03:14 PM] Registering platform 'homebridge-nest.Nest'
[12/20/2016, 4:03:14 PM] ---
[12/20/2016, 4:03:14 PM] Loaded plugin: homebridge-smartthings
[12/20/2016, 4:03:14 PM] Registering platform 'homebridge-smartthings.SmartThings'
[12/20/2016, 4:03:14 PM] ---
[12/20/2016, 4:03:14 PM] Loaded config.json with 0 accessories and 3 platforms.
[12/20/2016, 4:03:14 PM] ---
[12/20/2016, 4:03:14 PM] Loading 3 platforms...
[12/20/2016, 4:03:14 PM] Initializing Nest platform...
[12/20/2016, 4:03:14 PM] Fetching Nest devices.
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[12/20/2016, 4:03:14 PM] [SmartThings] Fetching Smart Things devices.
[12/20/2016, 4:03:14 PM] Initializing cmdSwitch2 platform...
[12/20/2016, 4:03:14 PM] Initializing platform accessory 'Smarter Coffee'...
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group sensor, Name Front Door, ID 4603a3a7-266f-431b-b723-b6c940487213
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group switch, Name Xmas Tree, ID 93279a88-ddaa-4c34-b8e4-dad3c40d20b8
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group sensor, Name Movement Lounge, ID 3daedeae-ef9a-4e8b-88bc-e419fb5113e3
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group switch, Name Xmas lights hallway, ID ed25a4ed-2285-431d-b9b0-5af6f6645b4a
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group sensor, Name Alisha's Keys, ID 70f2eb3b-d271-4c14-b053-951fe476397e
[12/20/2016, 4:03:14 PM] [SmartThings] Device Added - Group sensor, Name Syndi's Keys, ID fc55847c-2cea-4826-9b4a-061023a42be4
[12/20/2016, 4:03:14 PM] [SmartThings] Unknown Capabilities: ["Health Check","Tone","Signal Strength"]
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Front Door'...
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Xmas Tree'...
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Movement Lounge'...
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Xmas lights hallway'...
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Alisha's Keys'...
[12/20/2016, 4:03:14 PM] [SmartThings] Initializing platform accessory 'Syndi's Keys'...
[12/20/2016, 4:03:14 PM] Failed to determine Smarter Coffee state.
[12/20/2016, 4:03:14 PM] Traceback (most recent call last):
  File "/Users/grahamduke/iBrew/ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/grahamduke/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/grahamduke/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

**Comment by Tristan79** [comment]
Does the command` ibrew dump web 10.0.0.99` (with your appliance ip) run in a terminal under your normal user account? Since I think its an user issue

its missing tornado package

`pip install tornado`

If you run homebridge as another user log in as that user and run make setup again.
If you run homebridge as root, run `sudo pip install tornado` also any triggers set use
`sudo ibrew trigger ...` or again login as the right user to write to the right config file. 

Which system do you use? OSX, linux flavoure?

**Comment by asharun** [comment]
only myself and the misses have logins i'm the admin using OSX 

ran sudo pip install tornado and got the following:

The directory '/Users/grahamduke/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/grahamduke/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: tornado in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: singledispatch in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: backports_abc>=0.4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from singledispatch->tornado)

have checked and I'm down as the admin so not sure who or what is the owner of the directory?

Cheers

Graham

**Comment by asharun** [comment]
Grahams-Mac-mini:~ grahamduke$ ibrew dump web 10.0.0.99
-bash: ibrew: command not found

**Comment by asharun** [comment]
Grahams-Mac-mini:~ grahamduke$ sudo ibrew trigger
Password:
sudo: ibrew: command not found
Grahams-Mac-mini:~ grahamduke$

**Comment by Tristan79** [comment]
did the [dmg](https://dl.dropboxusercontent.com/u/12474226/iBrew.dmg) worked? or did you run it from source? 

If its from source it is not linked to the ibrew in /usr/local/bin/

`ln -s /Users/grahamduke/iBrew/ibrew  /usr/local/bin/ibrew`

but first verify if ibrew is there by running it

`/Users/grahamduke/iBrew/ibrew`

or go to you iBrew folder and run 
`./ibrew`

**Comment by asharun** [comment]
Hi yes the dmg worked fine.

ran /Users/grahamduke/iBrew/ibrew and got the following: 

Grahams-Mac-mini:~ grahamduke$ /Users/grahamduke/iBrew/ibrew
Traceback (most recent call last):
  File "/Users/grahamduke/iBrew/ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/grahamduke/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/grahamduke/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

Then ran ./ibrew from ibrew folder and got this:

Grahams-Mac-mini:ibrew grahamduke$ ./ibrew
Traceback (most recent call last):
  File "./ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/grahamduke/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/grahamduke/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

then ran ln -s /Users/grahamduke/iBrew/ibrew /usr/local/bin/ibrew and got the following:

Grahams-Mac-mini:ibrew grahamduke$ ln -s /Users/grahamduke/iBrew/ibrew /usr/local/bin/ibrew
ln: /usr/local/bin/ibrew: File exists

**Comment by Tristan79** [comment]
Ok, if you can run the dmg, then you can try to run the precompiled version of ibrew command line in the app package, ie. if you move the app into Applications the command will be:

`/Applications/iBrew.app/Contents/MacOS/iBrewConsole`

try to run that...i have no idea why it does not want to run the source due to a missing python package... it seems installed :-)

The only thing i could find online is:

> A common problem is having multiple Python interpreters, or multiple Python environments, installed. "pip" and "python" may use different environments. Try installing Tornado like this:


```
python -m pip install tornado
```

**Comment by asharun** [comment]
Hi Tristan

1st things 1st ran /Applications/iBrew.app/Contents/MacOS/iBrewConsole and this worked, then ran python -m pip install tornado and got the following:

Requirement already satisfied: tornado in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: singledispatch in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: backports_abc>=0.4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from singledispatch->tornado)

So looks like it is all installed ok.

Ran Homebridge but still coming up with same issue.   Will have another look at this in the morning, might look at removing python and tornado and installing from scratch.

Many thanks

Graham

**Comment by Tristan79** [comment]
well i suggest, replacing

 "on_cmd": "/Users/Tristan/Coding/iBrew/ibrew start 10.0.0.99",

into

 "on_cmd": "/Applications/iBrew.app/Contents/MacOS/iBrewConsole start
10.0.0.99",

(and the other two commands)

in the homebridhe config file... no need to muck about with python...

and add a symlink:

rm /usr/local/bin/ibrew
ln -s /Applications/iBrew.app/Contents/MacOS/iBrewConsole
/usr/local/bin/ibrew

**Comment by asharun** [comment]
Hi Tristan

added /Applications ... to the three lines and now looks to work, appears to see the coffee machine without error. Yey!!!

Not working yet though as press on in HomeKit and does nothing.

Going to look at adding the symlink in the morning, brain starting to give up ;-)

Many many thanks for your help really appriciated.

Graham

**Comment by asharun** [comment]
Ok so had to have a go...

did the symlink all looks ok,

when i ran homebridge and press on for the coffee machine (in homekit) homebridge shows the following happening:

[12/20/2016, 10:05:24 PM] Smarter Coffee is off.
[12/20/2016, 10:05:29 PM] Turning on Smarter Coffee took too long, assuming success.
[12/20/2016, 10:05:41 PM] Smarter Coffee is turned on.
[12/20/2016, 10:05:41 PM] Smarter Coffee is off.

however the coffee machine does not do anything

two steps forward on back

**Comment by asharun** [comment]
as a note when I try to run ibrew from the applications folder it now says "The applicaiton "iBrew" is not open anymore." not sure what has changed

**Comment by asharun** [comment]
forget the last message the new install had triggered os to block it, sorted that but still not running the coffee machine

**Comment by Tristan79** [comment]
try to run the individual commands to see what happens.  

/Applications/iBrew.app/Contents/MacOS/iBrewConsole start 10.0.0.99
/Applications/iBrew.app/Contents/MacOS/iBrewConsole stop (your ip ofcourse)
/Applications/iBrew.app/Contents/MacOS/iBrewConsole status (your ip)

homebridge runs those also...

make sure you selected filter in the smarter app, such that you do not spill any beans :-)

sleeping time for me :-)
