### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID

### ISSUE THREAD

**Issue by DJay-X** [Tristan79/iBrew#50]
Hi and in advance sorry for maybe some stupid questions. I'm new to homebridge and not a developer. So everything I got to run was with long passion.

Today I received my Smarter iKettle 2.0 and as a homebridge user my first thought was to get the Kettle connected to it.
So installed https://github.com/nferro/homebridge-http-json and https://github.com/luisiam/homebridge-cmdswitch2

In my config.json I added the IP of the Kettle and the Serial number like the following.

}, {
                  "platform": "cmdSwitch2",
                  "switches": [{
                               "name": "iKettle 2.0",
                               "on_cmd": "/Users/Tristan/Coding/iBrew/ibrew start xxx.xxx.xxx.xx",
                               "off_cmd": "/Users/Tristan/Coding/iBrew/ibrew stop xxx.xxx.xxx.xx",
                               "state_cmd": "/Users/Tristan/Coding/iBrew/ibrew status xxx.xxx.xxx.xx | grep 'busy'",
                               "manufacturer": "iBrew",
                               "model": "iBrew iKettle 2.0",
                               "serial": "4915SMKxxxxxx",
                               "polling": true,
                               "interval": 1
}]
                  }, {

iBrew is installed on macOS on my iMac. 
Homebridge runs on my Raspberry Pi 2 but now I get an error and the hombridge stops.
What am I doing wrong or what do I have to do in the correct way?
Thanks in advance for any reply.

[2017-2-28 21:55:50] Initializing platform accessory 'iKettle 2.0'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 3e0ab985-1394-46aa-8dff-3d0a97605bed
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:189:7)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:155:8)
    at cmdSwitchPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:67:14)
    at cmdSwitchPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:36:37)
    at emitNone (events.js:86:13)
    at API.emit (events.js:186:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

**Comment by Tristan79** [comment]
If iBrew is running on a different computer then homebridge, it won't work using the command line interface, I would suggest looking into 

https://github.com/Tristan79/iBrew/issues/44#issuecomment-272655177

You're probably have something in you're homebridge file with the same id...

**Comment by DJay1** [comment]
> You're probably have something in you're homebridge file with the same id...

Thanks Tristan. I figured out to get iBrew work directly on the Raspberry which is of course better.
It worked great for a couple of days but out of the blue I got the Error Message again "Cannot add a bridged Accessory with the same UUID as another bridged Accessory".
As a Newbie I have to ask where do I have to change something? In the config.json I just added the lines as described.
Is there a conflict when I have iBrew on Mac and Raspberry run simultaneously?
Homebridge only runs on the Pi.
As the serial in the config.json I used the actually serial from the Kettle.
Thanks in advance

`"platform": "cmdSwitch2",
                  "switches": [{
                               "name": "Wasserkocher",
                               "on_cmd": "/usr/local/bin/ibrew start",
                               "off_cmd": "/usr/local/bin/ibrew stop",
                               "state_cmd": "/usr/local/bin/ibrew status | grep 'busy'",
                               "manufacturer": "iBrew",
                               "model": "iBrew iKettle 2.0",
                               "serial": "xxxxxxxxx",
                               "polling": true,
                               "interval": 1
`

**Comment by Tristan79** [comment]
Ah, well I am not really familiar with homebridge and their plugins. You
should probably google for (the term ""Cannot add a bridged Accessory with
the same UUID as another bridged Accessory"" it results in many hits, fast
browsing through them, it's probably a error in the homebridge config file.

There should be no conflict between the mac version and the pi version...
But remember the appliance itself can only take a limit amount (around 2 to
7 depending how you use it) Luckily, if you have too many connection you
will notice, the device will reset itself... (and bleep)...

Homebridge also runs on the mac... :-)

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS
https://brew.sh
and something like...
https://changelog.com/posts/install-node-js-with-homebrew-on-os-x

Tristan
