### ISSUE TITLE
Error in detection

### ISSUE THREAD

**Issue by DJDangerousDan** [Tristan79/iBrew#52]
Hi, I have been compiling the source myself on a Windows 10, I've spent a good day trying to get it to play ball but to no joy. Once complied and installed and I run the "ibrew list" or just ibrew from the command line I get the following: 

2017-04-17 21:13:07,618 - DEBUG - 'NoneType' object has no attribute 'group'
2017-04-17 21:13:07,618 - DEBUG - Traceback (most recent call last):
  File "iBrewConsole.py", line 105, in web
  File "iBrewWeb.py", line 1407, in run
  File "iBrewWeb.py", line 1253, in autoconnect
  File "smarter\SmarterProtocol.py", line 1890, in find_devices
  File "smarter\SmarterProtocol.py", line 1911, in get_mac_for_device
AttributeError: 'NoneType' object has no attribute 'group'

2017-04-17 21:13:07,618 - INFO - iBrew: Failed to run Web Interface & REST API on port [:2080]

Also when I run ibrewui I get this in the logs:

2017-04-17 21:03:41,572 [INFO] GUI Started
2017-04-17 21:03:41,575 [ERROR] Web Server: Couldn't open socket on port :2080
2017-04-17 21:03:41,575 [DEBUG] 
2017-04-17 21:03:41,575 [INFO] iBrew: Failed to run Web Interface & REST API on port 2080

Couple of things I do know port 2080 is not blocked or in use.
I do have the latest ibrew from github
ikettle is on the same network/subnet
kettle has a static IP
same thing happens even if I connect directly to the kettle

I'm going to keep plugging away but any guidance will be gratefully received.

Thanks in advance
Dan

**Comment by Tristan79** [comment]
I think it the latest pull request... which is bothering you

change 

https://github.com/Tristan79/iBrew/blob/master/source/smarter/SmarterProtocol.py#L1902

def get_mac_for_device(self,target):
        pid = subprocess.Popen(["ping", "-c", "1", target], shell=False, stdout=subprocess.PIPE)

into 

def get_mac_for_device(self,target):
        return
        pid = subprocess.Popen(["ping", "-c", "1", target], shell=False, stdout=subprocess.PIPE)

until I have it fixed.... (could take a while :-)
