### ISSUE TITLE
Error Domoticz setup on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by Cryonic90** [Tristan79/iBrew#55]
I'm getting an error while trying to setup the Domoticz connection on Ubuntu server:
patrick@ESPRIMO:~/iBrew$ ibrew domoticz ikettle 0.0.0.0:8080

  Starting please wait...

iBrew: Domoticz Setup

Traceback (most recent call last):
  File "/home/patrick/iBrew/source/iBrewConsole.py", line 931, in execute
    Domoticz.setup(self.client,arguments[0])
  File "/home/patrick/iBrew/source/iBrewDomoticz.py", line 180, in setup
    client.device_type()
  File "/home/patrick/iBrew/source/smarter/SmarterInterface.py", line 5014, in device_type
    self.__read()
  File "/home/patrick/iBrew/source/smarter/SmarterInterface.py", line 2185, in __read
    message = self.__read_message()
  File "/home/patrick/iBrew/source/smarter/SmarterInterface.py", line 2163, in __read_message
    raise SmarterError(0,"Could not read message") # (" + msg + ")")
SmarterError

iBrew: Command Failed

The web interface works and I can manually add switches to domoticz which will call the iBrew API and that works too, but this auto setup doesn't work unfortunately, am I doing something wrong?

**Comment by Tristan79** [comment]
No idea, will look into this when I setup my own kettles with domoticz. For now just use the manual mode.
