### ISSUE TITLE
Kettle keeps disconnecting

### ISSUE THREAD

**Issue by lukefairbank** [Tristan79/iBrew#63]
Hi,
I have been using ibrew with my kettle and coffee machine for a few years.
I have added everything to a Home Assistant instance running on hassio.
The issue I am seeing is after about 20 mins the web server (which I have to use with hassio), can't connect to the kettle anymore. I get the following error when sending a command;

2020-04-19 10:56:25,544 - ERROR - Uncaught exception GET /api/192.168.0.221/start (192.168.0.89)
HTTPServerRequest(protocol='http', host='192.168.0.89:2080', method='GET', uri='/api/192.168.0.221/start', version='HTTP/1.1', remote_ip='192.168.0.89', headers={'Host': '192.168.0.89:2080', 'Accept': '*/*', 'User-Agent': 'curl/7.67.0'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/app/iBrew/source/iBrewWeb.py", line 821, in get
    client.device_start()
  File "/home/app/iBrew/source/smarter/SmarterInterface.py", line 5082, in device_start
    if self.isKettle:   self.kettle_heat_settings()
  File "/home/app/iBrew/source/smarter/SmarterInterface.py", line 5334, in kettle_heat_settings
    self.__send_command(Smarter.CommandHeatDefault)
  File "/home/app/iBrew/source/smarter/SmarterInterface.py", line 2260, in __send_command
    self.__send(Smarter.number_to_raw(id) + arguments + Smarter.number_to_raw(Smarter.MessageTail))
  File "/home/app/iBrew/source/smarter/SmarterInterface.py", line 2277, in __send
    raise SmarterError(0,"Could not write message not connected")
SmarterError

If I restart the web server then it works for another 20 mins or so before the issue starts again. I havent seen this happen with the coffee machine though, that still works after this error starts.
Any help would be much appreciated.

**Comment by Tristan79** [comment]
One of the possibilities is wifi strength.

Both the coffee machine and my kettle in the kitchen does that, sometimes,  think it has to do with low wifi signal strength. If the network is down for to long the machines reset themselves for some reason,... very annoying... The kettle in the attic rooms keeps working though... much closer to an access point.

Another possibility is all the newer versions of the python packages after a couple of years.
You can see the original versions of the packages in the requirements file. But that all require some python package management. If you are in to that (definitly a virtual environment)

**Comment by lukefairbank** [comment]
Thanks for the suggestion, I'll look into it

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by thexperiments** [comment]
Any news here? I have the same issue, Kettle not reachable after some time.
Restarting the server fixes it so it is not an issue with the wifi connection in general (sure the disconnect itself might be).

Shouldn't it be possible to reconnect just like it seems to be done on server start if a command can't be sent due to the connection being no longer established? 
Is there a way to trigger a reconnect via the API?

**Comment by thexperiments** [comment]
Hmm there seems to be an auto reconnect... 

            self.threadAutoConnect = threading.Timer(15, self.autoconnect)

could it be that the sensor (rest request) pulling the status every 20s somehow is causing a different problem?

**Comment by Tristan79** [comment]
No the reconnect is for if it looses the connection to the coffee/kettle machine. Like the situation above. And you can have many clients for iBrew, but only one connection to machine (the esp chip is limited) Regardless if the wifi is good. Maybe (probably) there is a bug in ibrew in which the thread has crashed and the autoConnect is not called for some reason.  

Will look into it (hopefully) when the next autumn holiday when my new office is finished. And I have a place to work. I encountered the same thing the last time I tried to set the machines up. Both my kettles and my coffee machine are collecting dust at the moment waiting to be set up properly. 

I was planning on doing a final version of iBrew and make all the executables again, incorporating all the bug fixes and pull/feature request I got the last couple of years.  I hope I can read my code since this was my first python project, and the six months it took to write it I knew where everything was... now it looks like some strangers code :-)

For boosting Wifi strength to the max, thanks to https://github.com/avast/ioc/issues/12

The protocol is:

`<0x69> <RFPOWER 0-82> <0x7e>`

i think the command on the command line to set wifi to full power is on the kettle or the coffee maker is: 

`ibrew 69827e`

but havent tried it yet.

About the wifi reconnect. There maybe coming a patched firmware for at least the coffee machine (not from smarter). Also see:

https://github.com/avast/ioc/issues/12

**Comment by Tristan79** [comment]
Maybe another solution is to use the included packages. I think it is a problem with a newer tornado package.
I changed the requirements file to fix it to the version that worked before.
