### ISSUE TITLE
Static IPs of appliances

### ISSUE THREAD

**Issue by DennisVonDerBey** [Tristan79/iBrew#70]
Hey, I am currently rebuilding my setup and went with a separate IOT network. This leads to my Smarter appliances being on another IP space. Sadly the auto discovery cannot find them anymore, but direct connection works fine. Is there any way to start the `events web` mode with a predefined list of my devices? I searched everywhere and cannot find a solution... :(

**Comment by Tristan79** [comment]
No. There is no list...

### Option I

Try running multiple instances of ibrew on different ports. Do a git pull
see (temp) fix https://github.com/Tristan79/iBrew/commit/3c393fb9bd739fe61f1918d96a667e1710c05c9b

Try running on the pi (or other pc who has access to both networks)

`./ibrew web "":2080 ipkettle:2081`

and in another terminal

`./ibrew web "":2090 ipcoffee:2081`


You should have then two rest api running, one on port 2080 and the other on port 2090,

This also means two systemd iBrew.service files to auto start (example: iBrewKettle.service and iBrewCoffee.service reflecting the different ports). 

Domoticz will support it, have no idea about home assistant/homebridge/etc...probably.


### Option II

Forward your network traffic of the smarter devices from and to port 2081 (udp & tcp) from one network to the other 
(also ibrew udp is using broadcast,  lets say you have a 192.168.0.1/255.255.255.0 network, then the broadcast address is 192.168.0.255. Also 255.255.255.255 is the broadcast address of the zero network (0.0.0.0), google it)

this last option is probably better, but I have no idea how to do that...  
port forwarding, broadcast address. you have to google it...

https://forum.openwrt.org/t/lan-vlan-access-to-raspberry-pi-server-on-a-separate-vlan/58721
https://magnusljadas.wordpress.com/2013/09/15/raspberry-pi-vlan-routing/


let me know which works and if you choose the last option how you did it...

**Comment by DennisVonDerBey** [comment]
Wow thanks for you input! The solution with the multiple instances sounds good to me, as I am only using it controlled by OpenHab and I will just pinpoint it to the right one.

Sadly the execution of `./ibrew web "":2080 ipkettle:2081` fails for me. It starts, but the connection then fails:

`2020-12-19 23:36:12,974 - DEBUG - [Errno 111] Connection refused
2020-12-19 23:36:12,976 - ERROR - [192.168.3.244] Could not connect to ipkettle:2080
iBrew: Registered bonjour server: openHABian:_ibrew._tcp.:(port 2080)
No coffee machine or kettle found
2020-12-19 23:36:15,403 - DEBUG - Traceback (most recent call last):
  File "/opt/iBrew/iBrew/source/smarter/SmarterInterface.py", line 2413, in connect
    self.__socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused`


Even though every other command works connecting to the IP directly. All firewall rules have been given. It seems to me it has to do with the parameter in front of it? The IP the web interface should listen on.

Maybe you can also point me to the right code line where the discovery happens? I am not that great navigating python code and I just cannot find it. There should be a way to hardcode the device IPs right?

Thanks again for your help!

**Comment by Tristan79** [comment]
My mistake, currently again sick (not the pandemic kind) and very tired,
and I make a lot of mistakes being very tired.
That also why iBrew exists, I got sick and wrote this to have something to
do (and learn the ins and outs of python).
iBrew one of the few software written while lying down on the couch for 6
months :-)

Anyway...

I should have tested it with the autodetect feature fully disabled before
replying. So I disabled it...
Tested it... Found one lousy typo, a missing "s" :-)
Started two servers... Tested it again.

Don't forget to pull

https://github.com/Tristan79/iBrew/commit/95cb0b4
Tc2de24e0662646db87492e467458cea64
<https://github.com/Tristan79/iBrew/commit/95cb0b4c2de24e0662646db87492e467458cea64>

You maybe want to remove these two lines, depending if you log stuff...
probably not :)

https://github.com/Tristan79/iBrew/blob/95cb0b4c2de24e0662646db87492e467458cea64/source/smarter/SmarterProtocol.py#L1979
https://github.com/Tristan79/iBrew/blob/95cb0b4c2de24e0662646db87492e467458cea64/source/smarter/SmarterProtocol.py#L1980

Because the autodetect is not used...
If you do not log, then while testing ignore the message  No coffee machine
or kettle found

**Comment by Tristan79** [comment]
Also 

./ibrew web "":2080 ipkettle:2081

you should change ipkettle to the actual ip address of the ikettle or the coffee machine...

Else you will get an error like this as posted above.

```
2020-12-19 23:36:12,976 - ERROR - [192.168.3.244] Could not connect to ipkettle:2080 will probably never work
```

For example: if 192.168.3.1 is the ip of the iKettle start with:

```
./ibrew web "":2080 192.168.3.1
```

**Comment by DennisVonDerBey** [comment]
> you should change ipkettle to the actual ip address of the ikettle or the coffee machine...

Yes sorry I should've stated that I only changed the log line for the GitHub post. That contained the right IP :)

> My mistake, currently again sick (not the pandemic kind) and very tired,
and I make a lot of mistakes being very tired.
That also why iBrew exists, I got sick and wrote this to have something to
do (and learn the ins and outs of python).
iBrew one of the few software written while lying down on the couch for 6
months :-)

The dual instances work now! Again thank you for your hard work and I really hope you're gonna be okay. Your work really has the "overengineered & niche" usecase vibe. I mean this in the most positive way and I love it! Without it I wouldn't have bought the appliances.

> Make sure the ip address are made static addresses in your dhcp server. Because if they are dynamic and change when the iKettle loses power or wifi was down, it will fail.

Already done :)

**Comment by Tristan79** [comment]
Well I am still quiet surprised, that I accidentally made a lot of people happy with me fooling around trying to learn new stuff... :-) 
 
Enjoy. Merry Christmas and a happy new year!
